- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: yes

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
  become: yes

- name: install common utilities on Debian machines
  apt: pkg={{ item }} state=present
  tags: install
  become: yes
  with_items:
    - byobu
    - curl
    - git
    - build-essential
    - jid
    - jq
    - tmux
    - smem # Tool that does good job of figuring out "real" memory use of processes
    - automake
    - silversearcher-ag
    - mosh
    - fzf
    - ripgrep
    - kitty
    - luajit
    - python3
    - python3-pip
    - golang-go
      # For building nvim
    - ninja-build
    - gettext
    - libtool
    - libtool-bin
    - autoconf
    - automake
    - cmake
    - g++
    - pkg-config
    - unzip
    - curl
    - doxygen
    - zsh

##
# node.js installation (latest stable instead of Ubuntu's out-of-date one)
#
- name: Node.js | Run the debian setup.
  shell: "curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
  tags: nodejs
  become: yes

- name: Node.js | Install nodejs and npm
  apt: pkg={{ item }} state=present
  tags: nodejs
  become: yes
  with_items:
    - nodejs
# Install neovim w/ an appimage
# - name: Install neovim

# shell: "wget https://github.com/neovim/neovim/releases/download/stable/nvim.appimage -O /opt/nvim.appimage"
# become: yes

# - name: neovim permissions
# shell: "chmod u+x /opt/nvim.appimage"

- name: Clone pyenv
  ansible.builtin.git:
    repo: 'git@github.com:pyenv/pyenv.git'
    dest: ~/.pyenv


- name: Set login shell of user {{ ansible_env.USER }} to `/bin/zsh` with `usermod`
  ansible.builtin.command: usermod --shell /bin/zsh {{ ansible_env.USER }}
  become: true
  changed_when: false
