- name: Clone dotfiles repo and submodules
  ansible.builtin.git:
    repo: 'git@github.com:davad/dotfiles.git'
    dest: ~/dotfiles
  tags: dotfile

- name: install dotfiles
  ansible.builtin.file:
    src: "~/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  tags: dotfile
  loop:
    - .dir_colors
    - .gitconfig
    - .gitignore_global
    - .latexmkrc
    - .zplug
    - .zshrc

- name: Clone nvim config
  ansible.builtin.git:
    repo: 'git@github.com:davad/janus-plugged.git'
    dest: ~/.config/nvim
  tags: dotfile

