- name: Enable yarn
  ansible.builtin.shell: corepack enable
  become: yes

- name: Install Node.js utilities
  ansible.builtin.shell: yarn global add {{ item }}
  with_items:
    - neovim
    - typescript
